### ISSUE TITLE
Exec requests double-encode responses

### ISSUE THREAD

**Issue by KimBurgess** [PlaceOS/rest-api#10]
When executing a module method, the response provided is escaped a second time.

For example, a driver with the following method:
```crystal
def test
  { foo: "bar" }
end
```

Will return the following when invoked.
```
"\"{\\\"foo\\\":\\\"bar\\\"}\""
```

Tests for this look to be marked as pending atm too so wouldn't have been picked up there.

**Comment by PhilPearson** [comment]
as per ACA v1, shouldnt this also be wrapped within an array?

**Comment by stakach** [comment]
As the JSON parser in browsers requires everything to be an object or an array before parsing, I would take the response, wrap it in `[` `]` and then parse to prevent errors.

**Comment by KimBurgess** [comment]
@stakach I’m not sure if that is accurate. A _correctly_ encoded string, should always parse back out to the appropriate type, sans wrapping, even in the case of primitives.

For example
```javascript
JSON.parse(“1”)  // == 1
JSON.parse(“\”foo\””) == “foo”
```

Note this however would not work as it’s not a valid token
```javascript
JSON.parse(“foo”)  // computer says no
```

**Comment by stakach** [comment]
Nice, no need to wrap in an array anymore.
Everything returned is valid JSON
