### ISSUE TITLE
Add support for system.images

### ISSUE THREAD

**Issue by w-le** [PlaceOS/rest-api#100]
Similarly to how zones now have .map (svg) for use with frontend apps, it would be a common use case for apps to display a series of images associated with rooms, so makes sense for a new System property to be added `images[]` which would be an array of urls to raster images.

I know that images can already be linked in system.description markdown, but ideally we want a way for frontend apps and external apis to be able to get the image uris easily when present

**Comment by MrYuion** [comment]
@w-le, I've updated backoffice to allow for adding these images.
