### ISSUE TITLE
feat(healthcheck): fail healthcheck if redis connection becomes unavailable

### ISSUE THREAD

**Issue by w-le** [PlaceOS/rest-api#113]
I just had an instance of rest-api **v1.17.11** get into this state:
- api responses were OK for almost all requests made by backoffice (except ones that involve redis)
- healthcheck was passing
- However there must have been a redis connection issue - I believe the redis pod restarted on a different IP a few hours before this rest-api issue was reported (about 2021-03-15T23:00:00Z). 
redis pod previous status info is here: 
```
terminated
Reason: Completed - exit code: 0
Started at: 2021-03-15T01:32:47Z
Finished at: 2021-03-15T10:02:06Z
```

- api returns this error when attempting to list the Commands of any Module:
```
ERROR: Socket::ConnectError: Error connecting to 'redis-headless.redis:6379': Address not available (Redis::CannotConnectError)
  from app/lib/redis/src/redis/socket_wrapper.cr:10:5 in 'connect'
  from app/lib/redis-cluster/src/cluster/bootstrap.cr:47:7 in 'redis'
  from app/lib/redis-cluster/src/redis.cr:69:13 in 'connect!'
  from usr/share/crystal/src/indexable.cr:269:9 in '???'
  from app/lib/placeos-driver/src/placeos-driver/proxy/system.cr:44:5 in 'get__api_engine_v2_systems___sys_id_functions__module_slug'
  from usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from usr/share/crystal/src/http/server/request_processor.cr:50:11 in 'process'
  from usr/share/crystal/src/http/server.cr:498:5 in '->'
  from usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
```

Recreating the api pod immediately resolved the issue.

Can we change the api healthcheck such that it fails if there is any current connection issue with Redis? OR, is that already the current healthcheck behaviour in the current version? This way kubernetes will auto restart api so that it connect to the new redis ip.

Alternatively, how often is the ip resolved for the redis hostname? if it's currently resolved only once upon the first initialization redis cluster bootstrap, then perhaps changing this to resolve upon every cluster bootstrap would ensure the api pod never gets into this state and would not even need to be restarted to reconnect to redis.

**Comment by w-le** [comment]
Unfortunately the same issue occurred again today.

Interestingly Core had no issues reconnecting to Redis - hey @caspiano are there any differences between the implementation of the Redis client in core vs rest-api that may point to an easy change in rest-api such that it is able to reconnect to Redis seamlessly in cases where Redis is briefly unavailable?

**Comment by caspiano** [comment]
There isn't much difference, all interactions with redis are via the same `PlaceOS::Driver::Storage` interface or the underlying client of `PlaceOS::Driver::Storage`.

Looking into this.

**Comment by w-le** [comment]
More info that may or may not be helpful:

I was trying to reproduce the issue by restarting redis in a similar k8s environment (same client, uat instead of prod) but when doing this rest-api was able to reconnect without issues after redis was back up.

In this controlled test, during the brief redis downtime, rest-api will output this repeatedly as expected, and then connect fine afterwards
https://gist.github.com/w-le/8f424d1371fc7d9505789497967a41c9

So I'm not sure why the behaviour in this controlled test is different to that described in the OP. In fact we did not even see the same specific error type "Address not available (Redis::CannotConnectError)" outputted, even though that error was outputted both times when the issue occurred (Redis exits unexpected with code 0) in production.

**Comment by w-le** [comment]
unfortunately this happened again today.
Not yet sure why it can get stuck in this state while other times redis can restart and rest-api will reconnect to it just fine.

Maybe it's related to the number of open redis connections/files within the api container exceeding a maximum or something? I have previously seen a redis error stating "too many connections" in this instance.

```
evel=DEBUG time=2021-03-30T02:13:16Z source=place_os.api.session ws_request_id=1 sys_id=sys-GhPzxGRnmFJ module_name=Bookings index=1 name=bookings message=Session (bind)
level=WARN time=2021-03-30T02:13:16Z source=place_os.api.session sys_id=sys-GhPzxGRnmFJ module_name=Bookings index=1 name=bookings message=websocket binding could not find system
Socket::ConnectError: Error connecting to 'redis-headless.redis:6379': Address not available (Redis::CannotConnectError)
from app/lib/redis/src/redis/socket_wrapper.cr:10:5 in 'connect'
from app/lib/redis-cluster/src/cluster/bootstrap.cr:47:7 in 'redis'
from app/lib/redis-cluster/src/redis.cr:69:13 in 'connect!'
from usr/share/crystal/src/indexable.cr:269:9 in '???'
from app/lib/placeos-driver/src/placeos-driver/subscriptions/indirect_subscription.cr:44:5 in 'perform_subscribe'
from app/lib/placeos-driver/src/placeos-driver/subscriptions.cr:72:7 in 'bind'
from app/src/placeos-rest-api/session.cr:664:24 in '__send__'
from app/src/placeos-rest-api/session.cr:563:7 in '->'
from usr/share/crystal/src/primitives.cr:255:3 in 'run'
from app/src/placeos-rest-api/controllers/systems.cr:11:3 in '->'
from usr/share/crystal/src/primitives.cr:255:3 in 'process'
from usr/share/crystal/src/http/server.cr:498:5 in '->'
from usr/share/crystal/src/primitives.cr:255:3 in 'run'
from ???
```

**Comment by caspiano** [comment]
I'll add the healthcheck now.

We have had a file descriptor issue due to the creation of redis clients before.
@stakach could you investigate the redis connection issue?

**Comment by stakach** [comment]
`Address not available` is a failure to locate the redis server using DNS

The file descriptor errors we've had previously have been solved by upping descriptor limits and ensuring that there is only a single shared redis client.

* https://github.com/PlaceOS/core/issues/67
* https://github.com/place-labs/k8s-helm/issues/11
