### ISSUE TITLE
Debug messages stop when user has multiple sessions active

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/rest-api#129]
**Describe the bug**
When the same user account is used to access backoffice from multiple simultaneous sessions, driver debug messages cease to propagate in both.

**Your environment**
Recreated on `placeos-1.2104.3`.

**To Reproduce**
Begin debugging a module, auth on a second machine / browser and enable logging there also.

**Expected behavior**
Log messages should appear in both sessions.

**Additional context**
Noted during some site testing with @jeremyw24. Were able to reliable reproduce on the remote system, but likely worth a local repro to gather some more context.

**Comment by caspiano** [comment]
Cannot reproduce as of `1.2202.2`
