### ISSUE TITLE
Trigger Count Not Updated based on Systems

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/rest-api#130]
In systems, adding a trigger correctly increases the trigger count in the systems menu bar, however the systems count on the triggers page is not updated to reflect the number of systems a trigger is in.

![image](https://user-images.githubusercontent.com/4019090/117223509-2d44ce00-ae51-11eb-8b09-97da75cb7472.png)

![image](https://user-images.githubusercontent.com/4019090/117223525-346bdc00-ae51-11eb-9d28-daf3e3cffc0a.png)

**Comment by caspiano** [comment]
@MrYuion `../triggers/:id/instances` yields instances of the trigger for both zones and systems

**Comment by MrYuion** [comment]
Fixed in a95808d

**Comment by MrYuion** [comment]
Fixed in commit PlaceOS/backoffice@a95808dd
