### ISSUE TITLE
`x-total-count` incorrect for limited trigger request

### ISSUE THREAD

**Issue by MrYuion** [PlaceOS/rest-api#17]
<img width="697" alt="Screen Shot 2020-04-17 at 1 05 16 pm" src="https://user-images.githubusercontent.com/20103948/79527933-244d5700-80ac-11ea-813a-40b2b9d12b14.png">
<img width="679" alt="Screen Shot 2020-04-17 at 1 05 29 pm" src="https://user-images.githubusercontent.com/20103948/79527940-27e0de00-80ac-11ea-8698-ac783ec05b3e.png">

**Comment by stakach** [comment]
@MrYuion total count is the total number of triggers available.
That's independent of the range you've requested.

The `content-range` header specifies the range of your request
`0-1/2` which means items 0 to 1 (not inclusive) of a total of 2
