### ISSUE TITLE
Refactor `Edge` token flow to use `ApiKey`

### ISSUE THREAD

**Issue by caspiano** [PlaceOS/rest-api#174]
The current flow uses [custom api tokens](https://github.com/PlaceOS/rest-api/blob/master/src/placeos-rest-api/controllers/edges.cr#L32).

Edge tokens contain some metadata, such as the edge id and secret

As we now have the `ApiKey` flow, edge's token flow should be implemented with them.

- [x] PlaceOS/models https://github.com/PlaceOS/models/pull/141
  + [x] Create a dependent association to an `ApiKey`
  + [x] Store the `Edge` id in `ApiKey` for purpose of lookups
  
- [x] PlaceOS/core https://github.com/PlaceOS/core/pull/162
  + [x] Refactor edge client to use `X-API-KEY`

- [x] PlaceOS/rest-api https://github.com/PlaceOS/rest-api/pull/235
  + [x] Use `X-API-KEY` in `/v2/edges` endpoints
  + [x] Refactor or remove token related flow

**Comment by stakach** [comment]
the api keys being used as edge tokens could have the edge_id as the scope value
