### ISSUE TITLE
`Metadata` search

### ISSUE THREAD

**Issue by stakach** [PlaceOS/rest-api#250]
The use case is some `Metadata` is configured, like `user(metadata).workplace.default_group` and we want to find all the users that match some value of the `default_group` key in the `workplace` metadata (basically to any depth)

Thinking we implement a `index` method on the metadata controller that accepts some queries like:

`GET /api/engine/v2/metadata?association=user&key=workplace.default_group&equals=admins`
and then possibly a few different matching types

* `equals=admins`
* `starts_with=admin`
* `key_missing=true`

and always return the parent model in the results

definitely open to suggestions, at the moment thinking the query goes directly to the database? Or would elasticsearch be better?

## Alternative Query Implementation

Queries could be defined in the following format

`$query_type[$key]=$queried_value`

For example, if we want to look up metadata with a specific key, `group.admin` with the value equal to `true`

`equal[group.admin]=true`

## Related Issues

- Original discussion https://github.com/place-technology/suncorp-ntt/issues/183
- https://github.com/PlaceOS/models/issues/156

**Comment by w-le** [comment]
just wondering what the rough schedule/eta would be for this one?

**Comment by caspiano** [comment]
I'll get started on this tomorrow.
The feature should be available when we put out the next release, say early next week.

**Comment by caspiano** [comment]
@w-le looks after digging through some implementation details with @stakach, this is probably going to be quite a bit more complicated. The estimate above isn't accurate.

**Comment by caspiano** [comment]
Going to change this to next sprint, @w-le 
Scoped most of the required changes and it should be about a day of work.
