### ISSUE TITLE
triggers routes

### ISSUE THREAD

**Issue by stakach** [PlaceOS/rest-api#27]
The current systems triggers route `/api/engine/v2/systems/:sys_id/triggers/` doesn't work well for listing the systems a particular trigger is a member of.

There are two things we want from this route:
1. The list of SystemTriggers attached to a system (route does this fine)
2. The list of SystemTriggers referencing a particular trigger (which systems have a trigger)

As the route does not work for point 2, I feel it should be something like:

 `/api/engine/v2/triggers/instances` with a `system_id` and `trigger_id` filter on the index route.

This came out of a discussion with @MrYuion earlier today.

**Comment by MrYuion** [comment]
Wouldn't something like `/api/engine/v2/triggers/:trigger_id/instances` be a slightly better route?

**Comment by stakach** [comment]
That would work if we want to add a new route for listing the systems a trigger is in.
I'm open to either, just adding that new route or modify the existing route to handle both.

Your suggestion is probably simpler @MrYuion
