### ISSUE TITLE
Module inconsistency

### ISSUE THREAD

**Issue by caspiano** [PlaceOS/rest-api#75]
Inconsistency observed in module logic

## Steps to reproduce

1. add _existing_ module from system *A* to a _new_ system *B*
1. remove module from system *A*
1. module cannot be added to *A*, it *should* be
1. module from *A* in driver's modules tab, it *shouldn't* be
1. module from *B* not in driver's modules tab, it *should* be

## Relevant API calls

1. PUT `/systems/${B}/module/${module}`
1. DELETE `/systems/${A}/module/${module}`
1. PUT `/systems/${A}/module/${module}`
1. GET `/modules?driver_id=${driver}`

**Comment by caspiano** [comment]
## 3

It appears the inability to add a module after deletion is caused by PlaceOS/backoffice/issues/122

## 4 & 5

This is a rendering issue. Currently only the directly associated System is rendered.

We should either...
+ remove the `System` column on the `Driver`'s `Module` tab
+ explicitly state the relationship
+ perform the same request as on `Module`'s `Systems` tab

**Comment by caspiano** [comment]
@w-le happy to close this off?

**Comment by w-le** [comment]
Yep, thanks!
