### ISSUE TITLE
Modules not filtering correctly

### ISSUE THREAD

**Issue by PhilPearson** [PlaceOS/rest-api#81]
Initially raised here https://github.com/PlaceOS/backoffice/issues/152#issue-767100685

Querying for modules always returns ALL modules ignoring filter parameter.

**Comment by caspiano** [comment]
Thanks for the issue, Phil
Do you know when this issue arose?

This is likely a component of PlaceOS/rubber-soul/issues/15

**Comment by PhilPearson** [comment]
No sorry, not sure I've ever tried filtering this list before.
